import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useSession, signIn, signOut } from "next-auth/react";
import { Icon } from "@iconify/react";
import Image from "next/image";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="box-border flex h-screen w-screen bg-background">
        <div className="grid h-full flex-1 place-items-center bg-primary ">
          <Image src="/assets/gift.svg" alt="" width={500} height={500} />
        </div>
        <div className="flex h-full flex-1 flex-col items-center justify-center p-4">
          <div className="flex w-4/5 flex-col gap-4 text-text1">
            <h1 className="text-4xl font-bold text-secondary">
              WEB REWARD SYSTEM
            </h1>
            <h2 className="font-sans text-xl">
              A full fledge solution to integrate reward base model in your
              website within 2 min!
            </h2>
          </div>
          <button
            className="mt-12 flex w-4/5 items-center justify-center gap-5 rounded-md py-2 font-semibold shadow-lg transition-all duration-100 ease-out hover:bg-primary hover:text-background"
            onClick={() => signIn()}
          >
            <Icon icon="flat-color-icons:google" />
            Sign in with Google
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
