import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useSession, signIn } from "next-auth/react";
import { Icon } from "@iconify/react";
import { useEffect } from "react";
import { useRouter } from "next/router";
import Lottie from "react-lottie";
import RewadLottie from "../assets/reward-landing.json";

const SignIn: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);
  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: RewadLottie,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  };

  const { data: session } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (session) {
      router.push("/home");
    }
  }, [session]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="box-border flex flex-col md:flex-row h-screen w-screen bg-background ">
        <div className="grid h-full flex-1 place-items-center bg-primary ">
          {/* <Image src="/assets/gift.svg" alt="" width={500} height={500} /> */}
          <div className="h-2/3 w-3/5">
            <Lottie options={defaultOptions} width="100%" height="100%" />
          </div>
        </div>
        <div className="flex h-full flex-1 flex-col items-center justify-center p-1 md:p-4">
          <div className="flex w-4/5 flex-col gap-4 text-text1">
            <h1 className="text-3xl md:text-4xl font-bold text-secondary">
              WEB REWARD SYSTEM
            </h1>
            <h2 className="font-sans text-xl">
              A full fledge solution to integrate reward base model in your
              website within 2 min!
            </h2>
          </div>
          <button
            className="mt-12 flex w-4/5 items-center justify-center gap-5 rounded-md py-2 font-semibold shadow-lg transition-all duration-100 ease-out hover:bg-primary hover:text-background"
            onClick={() => signIn()}
          >
            <Icon icon="flat-color-icons:google" />
            Sign in with Google
          </button>
        </div>
      </main>
    </>
  );
};

export default SignIn;
